<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.ActivateJobsResponse</code>
 */
class ActivateJobsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * list of activated jobs
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.ActivatedJob jobs = 1;</code>
     */
    private $jobs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ZeebeClient\ActivatedJob[]|\Google\Protobuf\Internal\RepeatedField $jobs
     *           list of activated jobs
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * list of activated jobs
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.ActivatedJob jobs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJobs()
    {
        return $this->jobs;
    }

    /**
     * list of activated jobs
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.ActivatedJob jobs = 1;</code>
     * @param \ZeebeClient\ActivatedJob[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJobs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ZeebeClient\ActivatedJob::class);
        $this->jobs = $arr;

        return $this;
    }

}

