<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.BrokerInfo</code>
 */
class BrokerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * unique (within a cluster) node ID for the broker
     *
     * Generated from protobuf field <code>int32 nodeId = 1;</code>
     */
    protected $nodeId = 0;
    /**
     * hostname of the broker
     *
     * Generated from protobuf field <code>string host = 2;</code>
     */
    protected $host = '';
    /**
     * port for the broker
     *
     * Generated from protobuf field <code>int32 port = 3;</code>
     */
    protected $port = 0;
    /**
     * list of partitions managed or replicated on this broker
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.Partition partitions = 4;</code>
     */
    private $partitions;
    /**
     * broker version
     *
     * Generated from protobuf field <code>string version = 5;</code>
     */
    protected $version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $nodeId
     *           unique (within a cluster) node ID for the broker
     *     @type string $host
     *           hostname of the broker
     *     @type int $port
     *           port for the broker
     *     @type \ZeebeClient\Partition[]|\Google\Protobuf\Internal\RepeatedField $partitions
     *           list of partitions managed or replicated on this broker
     *     @type string $version
     *           broker version
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * unique (within a cluster) node ID for the broker
     *
     * Generated from protobuf field <code>int32 nodeId = 1;</code>
     * @return int
     */
    public function getNodeId()
    {
        return $this->nodeId;
    }

    /**
     * unique (within a cluster) node ID for the broker
     *
     * Generated from protobuf field <code>int32 nodeId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNodeId($var)
    {
        GPBUtil::checkInt32($var);
        $this->nodeId = $var;

        return $this;
    }

    /**
     * hostname of the broker
     *
     * Generated from protobuf field <code>string host = 2;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * hostname of the broker
     *
     * Generated from protobuf field <code>string host = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * port for the broker
     *
     * Generated from protobuf field <code>int32 port = 3;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * port for the broker
     *
     * Generated from protobuf field <code>int32 port = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * list of partitions managed or replicated on this broker
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.Partition partitions = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPartitions()
    {
        return $this->partitions;
    }

    /**
     * list of partitions managed or replicated on this broker
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.Partition partitions = 4;</code>
     * @param \ZeebeClient\Partition[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPartitions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ZeebeClient\Partition::class);
        $this->partitions = $arr;

        return $this;
    }

    /**
     * broker version
     *
     * Generated from protobuf field <code>string version = 5;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * broker version
     *
     * Generated from protobuf field <code>string version = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

}

