<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.CancelWorkflowInstanceRequest</code>
 */
class CancelWorkflowInstanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * the workflow instance key (as, for example, obtained from
     * CreateWorkflowInstanceResponse)
     *
     * Generated from protobuf field <code>int64 workflowInstanceKey = 1;</code>
     */
    private $workflowInstanceKey = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $workflowInstanceKey
     *           the workflow instance key (as, for example, obtained from
     *           CreateWorkflowInstanceResponse)
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the workflow instance key (as, for example, obtained from
     * CreateWorkflowInstanceResponse)
     *
     * Generated from protobuf field <code>int64 workflowInstanceKey = 1;</code>
     * @return int|string
     */
    public function getWorkflowInstanceKey()
    {
        return $this->workflowInstanceKey;
    }

    /**
     * the workflow instance key (as, for example, obtained from
     * CreateWorkflowInstanceResponse)
     *
     * Generated from protobuf field <code>int64 workflowInstanceKey = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWorkflowInstanceKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->workflowInstanceKey = $var;

        return $this;
    }

}

