<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.CancelProcessInstanceRequest</code>
 */
class CancelProcessInstanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * the process instance key (as, for example, obtained from
     * CreateProcessInstanceResponse)
     *
     * Generated from protobuf field <code>int64 processInstanceKey = 1;</code>
     */
    protected $processInstanceKey = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $processInstanceKey
     *           the process instance key (as, for example, obtained from
     *           CreateProcessInstanceResponse)
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the process instance key (as, for example, obtained from
     * CreateProcessInstanceResponse)
     *
     * Generated from protobuf field <code>int64 processInstanceKey = 1;</code>
     * @return int|string
     */
    public function getProcessInstanceKey()
    {
        return $this->processInstanceKey;
    }

    /**
     * the process instance key (as, for example, obtained from
     * CreateProcessInstanceResponse)
     *
     * Generated from protobuf field <code>int64 processInstanceKey = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProcessInstanceKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->processInstanceKey = $var;

        return $this;
    }

}

