<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.CompleteJobRequest</code>
 */
class CompleteJobRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * the unique job identifier, as obtained from ActivateJobsResponse
     *
     * Generated from protobuf field <code>int64 jobKey = 1;</code>
     */
    protected $jobKey = 0;
    /**
     * a JSON document representing the variables in the current task scope
     *
     * Generated from protobuf field <code>string variables = 2;</code>
     */
    protected $variables = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $jobKey
     *           the unique job identifier, as obtained from ActivateJobsResponse
     *     @type string $variables
     *           a JSON document representing the variables in the current task scope
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the unique job identifier, as obtained from ActivateJobsResponse
     *
     * Generated from protobuf field <code>int64 jobKey = 1;</code>
     * @return int|string
     */
    public function getJobKey()
    {
        return $this->jobKey;
    }

    /**
     * the unique job identifier, as obtained from ActivateJobsResponse
     *
     * Generated from protobuf field <code>int64 jobKey = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setJobKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->jobKey = $var;

        return $this;
    }

    /**
     * a JSON document representing the variables in the current task scope
     *
     * Generated from protobuf field <code>string variables = 2;</code>
     * @return string
     */
    public function getVariables()
    {
        return $this->variables;
    }

    /**
     * a JSON document representing the variables in the current task scope
     *
     * Generated from protobuf field <code>string variables = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVariables($var)
    {
        GPBUtil::checkString($var, True);
        $this->variables = $var;

        return $this;
    }

}

