<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.DeployWorkflowRequest</code>
 */
class DeployWorkflowRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * List of workflow resources to deploy
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.WorkflowRequestObject workflows = 1;</code>
     */
    private $workflows;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ZeebeClient\WorkflowRequestObject[]|\Google\Protobuf\Internal\RepeatedField $workflows
     *           List of workflow resources to deploy
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * List of workflow resources to deploy
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.WorkflowRequestObject workflows = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWorkflows()
    {
        return $this->workflows;
    }

    /**
     * List of workflow resources to deploy
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.WorkflowRequestObject workflows = 1;</code>
     * @param \ZeebeClient\WorkflowRequestObject[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWorkflows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ZeebeClient\WorkflowRequestObject::class);
        $this->workflows = $arr;

        return $this;
    }

}

