<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.Partition</code>
 */
class Partition extends \Google\Protobuf\Internal\Message
{
    /**
     * the unique ID of this partition
     *
     * Generated from protobuf field <code>int32 partitionId = 1;</code>
     */
    private $partitionId = 0;
    /**
     * the role of the broker for this partition
     *
     * Generated from protobuf field <code>.gateway_protocol.Partition.PartitionBrokerRole role = 2;</code>
     */
    private $role = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $partitionId
     *           the unique ID of this partition
     *     @type int $role
     *           the role of the broker for this partition
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the unique ID of this partition
     *
     * Generated from protobuf field <code>int32 partitionId = 1;</code>
     * @return int
     */
    public function getPartitionId()
    {
        return $this->partitionId;
    }

    /**
     * the unique ID of this partition
     *
     * Generated from protobuf field <code>int32 partitionId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPartitionId($var)
    {
        GPBUtil::checkInt32($var);
        $this->partitionId = $var;

        return $this;
    }

    /**
     * the role of the broker for this partition
     *
     * Generated from protobuf field <code>.gateway_protocol.Partition.PartitionBrokerRole role = 2;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * the role of the broker for this partition
     *
     * Generated from protobuf field <code>.gateway_protocol.Partition.PartitionBrokerRole role = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkEnum($var, \ZeebeClient\Partition_PartitionBrokerRole::class);
        $this->role = $var;

        return $this;
    }

}

