<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

if (false) {
    /**
     * This class is deprecated. Use ZeebeClient\Partition\PartitionBrokerHealth instead.
     * @deprecated
     */
    class Partition_PartitionBrokerHealth {}
}
class_exists(Partition\PartitionBrokerHealth::class);
@trigger_error('ZeebeClient\Partition_PartitionBrokerHealth is deprecated and will be removed in the next major release. Use ZeebeClient\Partition\PartitionBrokerHealth instead', E_USER_DEPRECATED);

