<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.ProcessRequestObject</code>
 */
class ProcessRequestObject extends \Google\Protobuf\Internal\Message
{
    /**
     * the resource basename, e.g. myProcess.bpmn
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * the process definition as a UTF8-encoded string
     *
     * Generated from protobuf field <code>bytes definition = 2;</code>
     */
    protected $definition = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           the resource basename, e.g. myProcess.bpmn
     *     @type string $definition
     *           the process definition as a UTF8-encoded string
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the resource basename, e.g. myProcess.bpmn
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * the resource basename, e.g. myProcess.bpmn
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * the process definition as a UTF8-encoded string
     *
     * Generated from protobuf field <code>bytes definition = 2;</code>
     * @return string
     */
    public function getDefinition()
    {
        return $this->definition;
    }

    /**
     * the process definition as a UTF8-encoded string
     *
     * Generated from protobuf field <code>bytes definition = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDefinition($var)
    {
        GPBUtil::checkString($var, False);
        $this->definition = $var;

        return $this;
    }

}

