<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.ProcessMetadata</code>
 */
class ProcessMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * the bpmn process ID, as parsed during deployment; together with the version forms a
     * unique identifier for a specific process definition
     *
     * Generated from protobuf field <code>string bpmnProcessId = 1;</code>
     */
    protected $bpmnProcessId = '';
    /**
     * the assigned process version
     *
     * Generated from protobuf field <code>int32 version = 2;</code>
     */
    protected $version = 0;
    /**
     * the assigned key, which acts as a unique identifier for this process
     *
     * Generated from protobuf field <code>int64 processDefinitionKey = 3;</code>
     */
    protected $processDefinitionKey = 0;
    /**
     * the resource name (see: ProcessRequestObject.name) from which this process was
     * parsed
     *
     * Generated from protobuf field <code>string resourceName = 4;</code>
     */
    protected $resourceName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bpmnProcessId
     *           the bpmn process ID, as parsed during deployment; together with the version forms a
     *           unique identifier for a specific process definition
     *     @type int $version
     *           the assigned process version
     *     @type int|string $processDefinitionKey
     *           the assigned key, which acts as a unique identifier for this process
     *     @type string $resourceName
     *           the resource name (see: ProcessRequestObject.name) from which this process was
     *           parsed
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the bpmn process ID, as parsed during deployment; together with the version forms a
     * unique identifier for a specific process definition
     *
     * Generated from protobuf field <code>string bpmnProcessId = 1;</code>
     * @return string
     */
    public function getBpmnProcessId()
    {
        return $this->bpmnProcessId;
    }

    /**
     * the bpmn process ID, as parsed during deployment; together with the version forms a
     * unique identifier for a specific process definition
     *
     * Generated from protobuf field <code>string bpmnProcessId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBpmnProcessId($var)
    {
        GPBUtil::checkString($var, True);
        $this->bpmnProcessId = $var;

        return $this;
    }

    /**
     * the assigned process version
     *
     * Generated from protobuf field <code>int32 version = 2;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * the assigned process version
     *
     * Generated from protobuf field <code>int32 version = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * the assigned key, which acts as a unique identifier for this process
     *
     * Generated from protobuf field <code>int64 processDefinitionKey = 3;</code>
     * @return int|string
     */
    public function getProcessDefinitionKey()
    {
        return $this->processDefinitionKey;
    }

    /**
     * the assigned key, which acts as a unique identifier for this process
     *
     * Generated from protobuf field <code>int64 processDefinitionKey = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProcessDefinitionKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->processDefinitionKey = $var;

        return $this;
    }

    /**
     * the resource name (see: ProcessRequestObject.name) from which this process was
     * parsed
     *
     * Generated from protobuf field <code>string resourceName = 4;</code>
     * @return string
     */
    public function getResourceName()
    {
        return $this->resourceName;
    }

    /**
     * the resource name (see: ProcessRequestObject.name) from which this process was
     * parsed
     *
     * Generated from protobuf field <code>string resourceName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setResourceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->resourceName = $var;

        return $this;
    }

}

