<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.PublishMessageRequest</code>
 */
class PublishMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * the name of the message
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * the correlation key of the message
     *
     * Generated from protobuf field <code>string correlationKey = 2;</code>
     */
    protected $correlationKey = '';
    /**
     * how long the message should be buffered on the broker, in milliseconds
     *
     * Generated from protobuf field <code>int64 timeToLive = 3;</code>
     */
    protected $timeToLive = 0;
    /**
     * the unique ID of the message; can be omitted. only useful to ensure only one message
     * with the given ID will ever be published (during its lifetime)
     *
     * Generated from protobuf field <code>string messageId = 4;</code>
     */
    protected $messageId = '';
    /**
     * the message variables as a JSON document; to be valid, the root of the document must be an
     * object, e.g. { "a": "foo" }. [ "foo" ] would not be valid.
     *
     * Generated from protobuf field <code>string variables = 5;</code>
     */
    protected $variables = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           the name of the message
     *     @type string $correlationKey
     *           the correlation key of the message
     *     @type int|string $timeToLive
     *           how long the message should be buffered on the broker, in milliseconds
     *     @type string $messageId
     *           the unique ID of the message; can be omitted. only useful to ensure only one message
     *           with the given ID will ever be published (during its lifetime)
     *     @type string $variables
     *           the message variables as a JSON document; to be valid, the root of the document must be an
     *           object, e.g. { "a": "foo" }. [ "foo" ] would not be valid.
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the name of the message
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * the name of the message
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * the correlation key of the message
     *
     * Generated from protobuf field <code>string correlationKey = 2;</code>
     * @return string
     */
    public function getCorrelationKey()
    {
        return $this->correlationKey;
    }

    /**
     * the correlation key of the message
     *
     * Generated from protobuf field <code>string correlationKey = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCorrelationKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->correlationKey = $var;

        return $this;
    }

    /**
     * how long the message should be buffered on the broker, in milliseconds
     *
     * Generated from protobuf field <code>int64 timeToLive = 3;</code>
     * @return int|string
     */
    public function getTimeToLive()
    {
        return $this->timeToLive;
    }

    /**
     * how long the message should be buffered on the broker, in milliseconds
     *
     * Generated from protobuf field <code>int64 timeToLive = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeToLive($var)
    {
        GPBUtil::checkInt64($var);
        $this->timeToLive = $var;

        return $this;
    }

    /**
     * the unique ID of the message; can be omitted. only useful to ensure only one message
     * with the given ID will ever be published (during its lifetime)
     *
     * Generated from protobuf field <code>string messageId = 4;</code>
     * @return string
     */
    public function getMessageId()
    {
        return $this->messageId;
    }

    /**
     * the unique ID of the message; can be omitted. only useful to ensure only one message
     * with the given ID will ever be published (during its lifetime)
     *
     * Generated from protobuf field <code>string messageId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->messageId = $var;

        return $this;
    }

    /**
     * the message variables as a JSON document; to be valid, the root of the document must be an
     * object, e.g. { "a": "foo" }. [ "foo" ] would not be valid.
     *
     * Generated from protobuf field <code>string variables = 5;</code>
     * @return string
     */
    public function getVariables()
    {
        return $this->variables;
    }

    /**
     * the message variables as a JSON document; to be valid, the root of the document must be an
     * object, e.g. { "a": "foo" }. [ "foo" ] would not be valid.
     *
     * Generated from protobuf field <code>string variables = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVariables($var)
    {
        GPBUtil::checkString($var, True);
        $this->variables = $var;

        return $this;
    }

}

