<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

if (false) {
    /**
     * This class is deprecated. Use ZeebeClient\WorkflowRequestObject\ResourceType instead.
     * @deprecated
     */
    class WorkflowRequestObject_ResourceType {}
}
class_exists(WorkflowRequestObject\ResourceType::class);
@trigger_error('ZeebeClient\WorkflowRequestObject_ResourceType is deprecated and will be removed in the next major release. Use ZeebeClient\WorkflowRequestObject\ResourceType instead', E_USER_DEPRECATED);

