<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.WorkflowRequestObject</code>
 */
class WorkflowRequestObject extends \Google\Protobuf\Internal\Message
{
    /**
     * the resource basename, e.g. myProcess.bpmn
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * the resource type; if set to BPMN or YAML then the file extension
     * is ignored
     *
     * Generated from protobuf field <code>.gateway_protocol.WorkflowRequestObject.ResourceType type = 2;</code>
     */
    private $type = 0;
    /**
     * the process definition as a UTF8-encoded string
     *
     * Generated from protobuf field <code>bytes definition = 3;</code>
     */
    private $definition = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           the resource basename, e.g. myProcess.bpmn
     *     @type int $type
     *           the resource type; if set to BPMN or YAML then the file extension
     *           is ignored
     *     @type string $definition
     *           the process definition as a UTF8-encoded string
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the resource basename, e.g. myProcess.bpmn
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * the resource basename, e.g. myProcess.bpmn
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * the resource type; if set to BPMN or YAML then the file extension
     * is ignored
     *
     * Generated from protobuf field <code>.gateway_protocol.WorkflowRequestObject.ResourceType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * the resource type; if set to BPMN or YAML then the file extension
     * is ignored
     *
     * Generated from protobuf field <code>.gateway_protocol.WorkflowRequestObject.ResourceType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \ZeebeClient\WorkflowRequestObject_ResourceType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * the process definition as a UTF8-encoded string
     *
     * Generated from protobuf field <code>bytes definition = 3;</code>
     * @return string
     */
    public function getDefinition()
    {
        return $this->definition;
    }

    /**
     * the process definition as a UTF8-encoded string
     *
     * Generated from protobuf field <code>bytes definition = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDefinition($var)
    {
        GPBUtil::checkString($var, False);
        $this->definition = $var;

        return $this;
    }

}

