<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient\Partition;

use UnexpectedValueException;

/**
 * Describes the current health of the partition
 *
 * Protobuf type <code>gateway_protocol.Partition.PartitionBrokerHealth</code>
 */
class PartitionBrokerHealth
{
    /**
     * Generated from protobuf enum <code>HEALTHY = 0;</code>
     */
    const HEALTHY = 0;
    /**
     * Generated from protobuf enum <code>UNHEALTHY = 1;</code>
     */
    const UNHEALTHY = 1;

    private static $valueToName = [
        self::HEALTHY => 'HEALTHY',
        self::UNHEALTHY => 'UNHEALTHY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PartitionBrokerHealth::class, \ZeebeClient\Partition_PartitionBrokerHealth::class);

