<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient\Partition;

use UnexpectedValueException;

/**
 * Describes the Raft role of the broker for a given partition
 *
 * Protobuf type <code>gateway_protocol.Partition.PartitionBrokerRole</code>
 */
class PartitionBrokerRole
{
    /**
     * Generated from protobuf enum <code>LEADER = 0;</code>
     */
    const LEADER = 0;
    /**
     * Generated from protobuf enum <code>FOLLOWER = 1;</code>
     */
    const FOLLOWER = 1;
    /**
     * Generated from protobuf enum <code>INACTIVE = 2;</code>
     */
    const INACTIVE = 2;

    private static $valueToName = [
        self::LEADER => 'LEADER',
        self::FOLLOWER => 'FOLLOWER',
        self::INACTIVE => 'INACTIVE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PartitionBrokerRole::class, \ZeebeClient\Partition_PartitionBrokerRole::class);

