<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient\WorkflowRequestObject;

use UnexpectedValueException;

/**
 * Protobuf type <code>gateway_protocol.WorkflowRequestObject.ResourceType</code>
 */
class ResourceType
{
    /**
     * FILE type means the gateway will try to detect the resource type
     * using the file extension of the name field
     *
     * Generated from protobuf enum <code>FILE = 0;</code>
     */
    const FILE = 0;
    /**
     * extension 'bpmn'
     *
     * Generated from protobuf enum <code>BPMN = 1;</code>
     */
    const BPMN = 1;
    /**
     * extension 'yaml'
     *
     * Generated from protobuf enum <code>YAML = 2;</code>
     */
    const YAML = 2;

    private static $valueToName = [
        self::FILE => 'FILE',
        self::BPMN => 'BPMN',
        self::YAML => 'YAML',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResourceType::class, \ZeebeClient\WorkflowRequestObject_ResourceType::class);

